# ----------- CONFIGURABLE START -----------
title:            "liuliu-Blog"
description:      "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url:               https://liusxs.github.io/liuliu-Blog/ # 域名
signoff:          "liuliu" # Your name
facebook_appid:   #liberxue
google_analytics: #UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          liuliu-Blog/
    external:     false
  - name:         书籍
    url:          liuliu-Blog//book
    external:     false
  - name:         旅游
    url:          liuliu-Blog//road
    external:     false
  - name:         归档
    url:          liuliu-Blog//archives
    external:     false
  - name:         标签
    url:          liuliu-Blog//tags
    external:     false
  - name:         关于
    url:          liuliu-Blog//about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
